# SPDX-License-Identifier: GPL-2.0-only
obj-m += dtld_ib.o

dtld_ib-y := \
	dtld.o \
	dtld_verbs.o \
	dtld_pool.o \
	dtld_mr.o \
	dtld_cq.o \
	dtld_qp.o \
	dtld_queue.o \
	dtld_task.o \
	dtld_req.o \
	dtld_resp.o \
	dtld_comp.o \
	dtld_av.o \
	dtld_opcode.o \

